[features]
seeds = true
skip-lint = false

[programs.localnet]
terravault = "DoAFjsoY9Ws7ZTNCokpsYHyNho8Krj9nK5dQFCdgYQqM"

[programs.devnet]
terravault = "DoAFjsoY9Ws7ZTNCokpsYHyNho8Krj9nK5dQFCdgYQqM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
